update to chia-blockchain 1.8.1
Chia-Network/chia-nft-minting-tool pull request #31
Opened 2023-05-17 23:30 UTC by geoffwalmsley

- update to chia-blockchain 1.8.1
- update to chia-dev-tools 1.2.0
- fix import launcher puzzle from did wallet

2023-05-18 00:49 UTC, altendky requested changes

2023-05-18 00:49 UTC, altendky commented on setup.py
> +    "chia-blockchain>=1.8.0",
`chia-blockchain` doesn't make backwards compatible guarantees so `>=` is not generally a good idea.  If you have concluded this is compatible with 1.8.0 and 1.8.1 then you can do this.

```suggestion
    "chia-blockchain>=1.8.0,<=1.8.1",
```

I don't know that it is generally worthwhile though with `chia-blockchain`.

```suggestion
    "chia-blockchain==1.8.1",
```

2023-05-18 00:49 UTC, altendky commented on chianft/util/mint.py
> +                if coin.puzzle_hash == INTERMEDIATE_LAUNCHER_MOD_HASH
I don't immediately see how this is correct.  Maybe you could explain, or someone already familiar with it should review this.

2023-05-22 16:22 UTC, trepca approved these changes

2023-05-22 17:07 UTC, altendky approved these changes

2023-05-22 17:31 UTC, merged